print("Perform basic calculations")
print("Enter your first number: ")
num1 = input()
num1 = float(num1)
print("Enter your second number: ")
num2 = input()
num2 = float(num2)
sum = str(num1 + num2)
product = str(num1 * num2)
quotient = str(num1 / num2)
diff = str(num1 - num2)
print("The sum is "+sum)
print("The product is "+product)
print("The quotient is "+quotient)
print("The difference is "+diff)
